## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: "Loading Configuration/s"
      include_vars: "./{{ deployment }}"

    - name: "Loading Default Vars"
      include_vars: ./config/default_vars.yaml

    - name: "Initializating..."
      include_tasks: ./playbooks/init.yaml

    - name: "Installing Openshift"
      include_tasks: ./playbooks/openshift_install.yaml
      tags: install

    - name: "Configuring Openshift"
      include_tasks: ./playbooks/openshift_configure.yaml
      tags: config

    - name: "Generating Cluster Report"
      include_tasks: ./playbooks/report.yaml
