## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: "Loading Default Vars"
      include_vars: ./config/default_vars.yaml

    - name: "Loading Configuration/s"
      include_vars: "./{{ config }}"

    - name: "Install and Configure"
      include_tasks: ./playbooks/init.yaml
      loop_control:
        loop_var: cluster
      with_items:
        - "{{ clusters }}"
