## Red Hat Intel Openshift Lab config tool
################################################################################
## vim: noai:ts=2:sw=2

---
- name: "AWS - Print Profile"
  debug:
    msg: "Using {{ cluster.cloud.aws.profile.aws_account_name }} Profile"

# The following blocks are compared with 4.11 because the installer changes the way to obtain the credentials

- name: "AWS - Configuring Credentials for OCP installers <= 4.10"
  block:
  - name: "AWS - Set facts for OCP installers <= 4.10"
    set_fact:
      _cloud_profile: |
        export AWS_SHARED_CREDENTIALS_FILE=./aws_profile.cfg

  - name: "AWS - Generating config file"
    copy:
      content: |
        [default]
        aws_access_key_id = {{ cluster.cloud.aws.profile.aws_access_key_id }}
        aws_secret_access_key = {{ cluster.cloud.aws.profile.aws_secret_access_key }}
      dest: "{{ install_dir }}/aws_profile.cfg"
      force: true
  when:
    - cluster.version is version('4.11', '<')


- name: "AWS - Configuring Credentials for OCP installers >= 4.11"
  block:
  - name: "AWS - Set facts for OCP installers >= 4.11"
    set_fact:
      _cloud_profile: |
        export AWS_ACCESS_KEY_ID={{ cluster.cloud.aws.profile.aws_access_key_id }}
        export AWS_SECRET_ACCESS_KEY={{ cluster.cloud.aws.profile.aws_secret_access_key }}
  when:
    - cluster.version is version('4.11', '>=')

- name: "Preparing env"
  shell:
    cmd: |
      {{ _cloud_profile }}
