## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- name: "Configure HTPasswd - Creating OAuth Service"
  template:
    src: "{{ auth_htpasswd_template }}"
    dest: "{{ install_dir }}/oauth_htpasswd.yaml"

- name: "Configure HTPasswd - Setting Facts"
  set_fact:
    cluster_auth_provider: "htpasswd"

- name: "Configure HTPasswd - Creating htpasswd file"
  file:
    path: "{{ auth_htpasswd_file }}"
    state: touch

- name: "Configure HTPasswd - Adding user"
  shell: |
    htpasswd -b {{ auth_htpasswd_file }} {{ user.name }} {{ user.pass }}
  loop_control:
    loop_var: user
  with_items:
    - "{{ cluster.config.auth.users }}"

- name: "Configure HTPasswd - Installing HTPasswd provider"
  shell: |
    oc apply -f {{ install_dir }}/oauth_htpasswd.yaml
    oc create secret generic htpasswd-secret --from-file htpasswd={{ auth_htpasswd_file }} -n openshift-config
    true
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
