## Red Hat Intel Openshift Lab config tool
################################################################################
## vim: noai:ts=2:sw=2

---
- name: "Init - Creating cluster directory"
  file:
    path: "{{ install_dir }}"
    state: directory

- name: "Init - Generating install-config.yaml file"
  copy:
    content: "{{ cluster.spec | to_nice_yaml }}"
    dest: "{{ install_dir }}/install-config.yaml"

- name: "Init - Generating cluster-config.yaml file"
  copy:
    content: "{{ cluster.config | to_nice_yaml(indent=2) | indent(width=2)}}"
    dest: "{{ install_dir }}/cluster-config.yaml"
