## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- name: "Getting credentials from install output file"
  shell:
    cmd: "cat kubeadmin-password"
    chdir: "{{ install_dir }}/auth"
  register: credentials

- name: "Print Credentials"
  debug:
    msg:
      - "Cluster name: {{ cluster.name }}"
      - "URL: {{ console_url }} "
      - "User: kubeadmin "
      - "Pass: {{ credentials.stdout }} "
