## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- name: "Destroying cluster: {{ cluster.name }} @{{ console_url }}"
  shell:
    cmd: |
      export {{ _cloud_profile }}
      ./openshift-install destroy cluster --dir . --log-level=info
    chdir: "{{ install_dir }}"

- name: "Cleanning installation folder"
  file:
    path: "{{ install_dir }}"
    state: absent
