## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- name: "Report - Checking cluster data"
  stat:
    path: "{{ install_dir }}/auth"
  register: cluster_exists

- block:
  - name: "Report - Getting kubeadmin credentials"
    shell:
      cmd: "cat kubeadmin-password"
      chdir: "{{ install_dir }}/auth"
    register: credentials

  - name: "Report - Getting kubeconfig file"
    shell:
      cmd: "cat kubeconfig"
      chdir: "{{ install_dir }}/auth"
    register: kubeconfig

  - name: "Report - Getting cluster certificate key"
    shell:
      cmd: "cat *.key"
      chdir: "{{ install_dir }}/tls"
    register: cert_key

  - name: "Report - Getting cluster certificate"
    shell:
      cmd: "cat *.crt"
      chdir: "{{ install_dir }}/tls"
    register: cert_crt

  - name: "Report - Generating config report"
    template:
      src: "{{ report_template }}"
      dest: "{{ install_dir }}/report.md"

  - name: "Report - Print Credentials"
    debug:
      msg:
        - "Cluster name: {{ cluster.name }}"
        - "URL: {{ console_url }} "
        - "User: kubeadmin "
        - "Pass: {{ credentials.stdout }} "
  when:
    - cluster_exists.stat.exists
