## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- name: "Report - Generating config report"
  template:
    src: "{{ report_template }}"
    dest: "{{ install_dir }}/report.md"

- name: "Report - Getting credentials from install output file"
  shell:
    cmd: "cat kubeadmin-password"
    chdir: "{{ install_dir }}/auth"
  register: credentials

- name: "Report - Print Credentials"
  debug:
    msg:
      - "Cluster name: {{ cluster.name }}"
      - "URL: {{ console_url }} "
      - "User: kubeadmin "
      - "Pass: {{ credentials.stdout }} "
